---
- hosts: all
  gather_facts: true
  become: false
  vars_files:
    - group_vars/main.yml
    - group_vars/vault.yml

  tasks:
    - block:
      - name: Configure server to be CIS compliant
        include_role:
          name: ansible-lockdown.ubuntu20-cis
        vars:
          ubtu20cis_ipv6_required: true
          ubtu20cis_rule_1_1_1_2: false
          ubtu22cis_rule_5_3_1: false
          ubtu20cis_rule_5_3_2: false
          ubtu20cis_rule_5_3_3: false
          ubtu20cis_rule_5_3_4: false
          ubtu20cis_rule_5_3_5: false
          ubtu20cis_rule_5_3_6: false
          ubtu20cis_rule_5_3_7: false
          ubtu20cis_sshd:
            allow_users: "{{ ansible_user }}"
      become: true

    - name: Create dir for docker compose
      file:
        path: "/home/{{  ansible_user   }}/caddy"
        state: directory
        owner: "{{  ansible_user   }}"
        mode: 0775

    - name: copy caddy docker compose to server
      copy:
        src: files/docker-compose.yml
        dest: "/home/{{  ansible_user   }}/caddy/docker-compose.yml"

    - name: creating network
      shell: |
        docker network inspect caddy >/dev/null 2>&1 || \
        docker network create caddy

    - name: deploying caddy
      shell: |
        cd caddy && docker compose up -d

    #     Example:

    # - name: Git checkout
    #   ansible.builtin.git:
    #     repo: 'https://github.com/jstet/myrtle.git'
    #     dest: /home/{{  ansible_user   }}/myrtle
    #
    #
    # - name: Template docker compose to server
    #   template:
    #     src: "templates/docker-compose.yml"
    #     dest: "/home/{{  ansible_user   }}/myrtle/docker-compose.yml"

    # - name: deploying app
    #   shell: |
    #     cd myrtle && docker compose up -d


